name: CI

on:
  push: ~
  pull_request: ~
  workflow_dispatch: ~

jobs:
  tests:
    runs-on: ubuntu-latest

    name: "Test  PHP : ${{ matrix.php }}"

    strategy:
      fail-fast: false
      matrix:
        php: [ "5.3", "7.0", "8.0", "8.1", "8.2" ]

    steps:
      -
        uses: actions/checkout@v3

      -
        name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "${{ matrix.php }}"
          coverage: none

      -
        name: Run tests
        run: php test/ForceUTF8Test.php
